name: Version Management

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      increment_type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for version calculation
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Determine version increment
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "increment_type=${{ github.event.inputs.increment_type }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.head_commit.message }}" =~ ^(BREAKING CHANGE|major|MAJOR) ]]; then
          echo "increment_type=major" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.head_commit.message }}" =~ ^(feat|feature|minor|MINOR) ]]; then
          echo "increment_type=minor" >> $GITHUB_OUTPUT
        else
          echo "increment_type=patch" >> $GITHUB_OUTPUT
        fi
        
        echo "Current version: $(grep '__version__ = ' observables/_version.py | sed 's/.*"\([^"]*\)".*/\1/')"
        echo "Increment type: ${{ steps.version.outputs.increment_type }}"
    
    - name: Bump version
      run: |
        python scripts/version_manager.py auto ${{ steps.version.outputs.increment_type }}
    
    - name: Create Pull Request
      if: github.event_name == 'push'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: bump version to $(grep '__version__ = ' observables/_version.py | sed 's/.*"\([^"]*\)".*/\1/')"
        title: "chore: bump version to $(grep '__version__ = ' observables/_version.py | sed 's/.*"\([^"]*\)".*/\1/')"
        body: |
          This PR was automatically created to bump the version.
          
          **Version increment type:** ${{ steps.version.outputs.increment_type }}
          **New version:** $(grep '__version__ = ' observables/_version.py | sed 's/.*"\([^"]*\)".*/\1/')
          
          Changes:
          - Updated version in `observables/_version.py`
          - Updated version in `observables/__init__.py`
          - Updated version in `setup.py`
        
        branch: version-bump
        delete-branch: true
        base: main
